[package]
name = "advent2019"
version = "0.1.0"
authors = ["spoo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bit-array = "0.4.4" #aoc3
#typenum = "1.11.2"  #aoc3, bit-array
bitvec = "0.16.0"
